name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install NPM packages
      run: npm install

    - name: Fixup homepage
      id: fixup
      if: github.ref != 'refs/heads/main'
      run: echo "::set-output name=destination::$(python3 .github/scripts/fixup.homepage.py)"

    - name: test
      run: echo "${{ steps.fixup.outputs.destination }}"

    - name: Build project
      env:
        REACT_APP_TRACKING_ID: G-ZEPK0MGHLE
      run: npm run build

    - name: Deploy project to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        publish_dir: ./build
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: krizanka/krizanka.github.io
        #   keep_files: true
        # user_name: <username>
        # user_email: <username@email.com>
        #   cname: example.com

    - name: Deploy PR to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref != 'refs/heads/main'
      with:
        publish_dir: ./build
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: krizanka/krizanka.github.io
        destination_dir: ${{ steps.fixup.outputs.destination }}
        #   keep_files: true
        # user_name: <username>
        # user_email: <username@email.com>
        #   cname: example.com
